<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run()
    {
        // Predurčené produkty
        $products = [
            // Rings
            [
                'title'       => 'Sterling Silver Ring',
                'sku'         => 'RING-001',
                'slug'        => 'sterling-silver-ring',
                'price'       => 49.99,
                'discount'    => 0,
                'category'    => 'rings',
                'color'       => 'silver',
                'gender'      => 'unisex',
                'description' => 'Classic sterling silver ring with a polished finish.',
                'summary'     => 'Polished sterling silver ring',
            ],
            [
                'title'       => 'Gold-Plated Ring',
                'sku'         => 'RING-002',
                'slug'        => 'gold-plated-ring',
                'price'       => 59.99,
                'discount'    => 0,
                'category'    => 'rings',
                'color'       => 'gold',
                'gender'      => 'unisex',
                'description' => 'Elegant gold-plated ring coated over durable metal.',
                'summary'     => 'Elegant gold-plated ring',
            ],
            [
                'title'       => 'Rose Gold Infinity Ring',
                'sku'         => 'RING-003',
                'slug'        => 'rose-gold-infinity-ring',
                'price'       => 79.99,
                'discount'    => 0,
                'category'    => 'rings',
                'color'       => 'rose gold',
                'gender'      => 'unisex',
                'description' => 'Romantic infinity design in rose gold plating.',
                'summary'     => 'Romantic rose gold infinity ring',
            ],
            [
                'title'       => 'Diamond Solitaire Ring',
                'sku'         => 'RING-004',
                'slug'        => 'diamond-solitaire-ring',
                'price'       => 199.99,
                'discount'    => 0,
                'category'    => 'rings',
                'color'       => 'white',
                'gender'      => 'unisex',
                'description' => 'Stunning solitaire diamond set in white gold.',
                'summary'     => 'Solitaire diamond ring',
            ],
            [
                'title'       => 'Black Onyx Ring',
                'sku'         => 'RING-005',
                'slug'        => 'black-onyx-ring',
                'price'       => 29.99,
                'discount'    => 0,
                'category'    => 'rings',
                'color'       => 'black',
                'gender'      => 'unisex',
                'description' => 'Bold black onyx gemstone set in stainless steel.',
                'summary'     => 'Black onyx stainless steel ring',
            ],

            // Bracelets
            [
                'title'       => 'Leather Wrap Bracelet',
                'sku'         => 'BRACELET-001',
                'slug'        => 'leather-wrap-bracelet',
                'price'       => 34.99,
                'discount'    => 0,
                'category'    => 'bracelets',
                'color'       => 'brown',
                'gender'      => 'unisex',
                'description' => 'Genuine leather wrap bracelet with adjustable strap.',
                'summary'     => 'Adjustable leather wrap bracelet',
            ],
            [
                'title'       => 'Beaded Stretch Bracelet',
                'sku'         => 'BRACELET-002',
                'slug'        => 'beaded-stretch-bracelet',
                'price'       => 24.99,
                'discount'    => 0,
                'category'    => 'bracelets',
                'color'       => 'multicolor',
                'gender'      => 'unisex',
                'description' => 'Colorful beads strung on stretch cord for comfort.',
                'summary'     => 'Comfortable beaded stretch bracelet',
            ],
            [
                'title'       => 'Silver Chain Bracelet',
                'sku'         => 'BRACELET-003',
                'slug'        => 'silver-chain-bracelet',
                'price'       => 44.99,
                'discount'    => 0,
                'category'    => 'bracelets',
                'color'       => 'silver',
                'gender'      => 'unisex',
                'description' => 'Delicate silver chain bracelet with lobster clasp.',
                'summary'     => 'Delicate silver chain bracelet',
            ],
            [
                'title'       => 'Gold Bangle Bracelet',
                'sku'         => 'BRACELET-004',
                'slug'        => 'gold-bangle-bracelet',
                'price'       => 39.99,
                'discount'    => 0,
                'category'    => 'bracelets',
                'color'       => 'gold',
                'gender'      => 'unisex',
                'description' => 'Sleek gold bangle for a minimalist look.',
                'summary'     => 'Minimalist gold bangle bracelet',
            ],
            [
                'title'       => 'Charm Bracelet',
                'sku'         => 'BRACELET-005',
                'slug'        => 'charm-bracelet',
                'price'       => 49.99,
                'discount'    => 0,
                'category'    => 'bracelets',
                'color'       => 'silver',
                'gender'      => 'unisex',
                'description' => 'Customizable charm bracelet with 5 charms.',
                'summary'     => 'Customizable charm bracelet',
            ],

            // Necklaces
            [
                'title'       => 'Pearl Necklace',
                'sku'         => 'NECKLACE-001',
                'slug'        => 'pearl-necklace',
                'price'       => 69.99,
                'discount'    => 0,
                'category'    => 'necklaces',
                'color'       => 'white',
                'gender'      => 'unisex',
                'description' => 'Classic cultured pearl necklace on silk thread.',
                'summary'     => 'Classic cultured pearl necklace',
            ],
            [
                'title'       => 'Gold Pendant Necklace',
                'sku'         => 'NECKLACE-002',
                'slug'        => 'gold-pendant-necklace',
                'price'       => 59.99,
                'discount'    => 0,
                'category'    => 'necklaces',
                'color'       => 'gold',
                'gender'      => 'unisex',
                'description' => 'Gold pendant on a fine chain.',
                'summary'     => 'Gold pendant necklace',
            ],
            [
                'title'       => 'Silver Locket Necklace',
                'sku'         => 'NECKLACE-003',
                'slug'        => 'silver-locket-necklace',
                'price'       => 54.99,
                'discount'    => 0,
                'category'    => 'necklaces',
                'color'       => 'silver',
                'gender'      => 'unisex',
                'description' => 'Vintage-inspired silver locket necklace.',
                'summary'     => 'Vintage silver locket necklace',
            ],
            [
                'title'       => 'Rose Gold Choker Necklace',
                'sku'         => 'NECKLACE-004',
                'slug'        => 'rose-gold-choker-necklace',
                'price'       => 74.99,
                'discount'    => 0,
                'category'    => 'necklaces',
                'color'       => 'rose gold',
                'gender'      => 'unisex',
                'description' => 'Trendy rose gold choker with adjustable length.',
                'summary'     => 'Trendy rose gold choker necklace',
            ],
            [
                'title'       => 'Diamond Tennis Necklace',
                'sku'         => 'NECKLACE-005',
                'slug'        => 'diamond-tennis-necklace',
                'price'       => 149.99,
                'discount'    => 0,
                'category'    => 'necklaces',
                'color'       => 'white',
                'gender'      => 'unisex',
                'description' => 'Sparkling diamond tennis necklace in white gold.',
                'summary'     => 'Sparkling diamond tennis necklace',
            ],

            // Earrings
            [
                'title'       => 'Stud Earrings',
                'sku'         => 'EARRINGS-001',
                'slug'        => 'stud-earrings',
                'price'       => 19.99,
                'discount'    => 0,
                'category'    => 'earrings',
                'color'       => 'silver',
                'gender'      => 'unisex',
                'description' => 'Simple silver stud earrings.',
                'summary'     => 'Classic silver stud earrings',
            ],
            [
                'title'       => 'Hoop Earrings',
                'sku'         => 'EARRINGS-002',
                'slug'        => 'hoop-earrings',
                'price'       => 24.99,
                'discount'    => 0,
                'category'    => 'earrings',
                'color'       => 'gold',
                'gender'      => 'unisex',
                'description' => 'Medium-sized gold hoop earrings.',
                'summary'     => 'Medium gold hoop earrings',
            ],
            [
                'title'       => 'Blue Crystal Drop Earrings',
                'sku'         => 'EARRINGS-003',
                'slug'        => 'blue-crystal-drop-earrings',
                'price'       => 29.99,
                'discount'    => 0,
                'category'    => 'earrings',
                'color'       => 'blue',
                'gender'      => 'unisex',
                'description' => 'Elegant drop earrings with blue crystals.',
                'summary'     => 'Blue crystal drop earrings',
            ],
            [
                'title'       => 'Chandelier Earrings',
                'sku'         => 'EARRINGS-004',
                'slug'        => 'chandelier-earrings',
                'price'       => 89.99,
                'discount'    => 0,
                'category'    => 'earrings',
                'color'       => 'gold',
                'gender'      => 'unisex',
                'description' => 'Ornate chandelier earrings for special occasions.',
                'summary'     => 'Ornate chandelier earrings',
            ],
            [
                'title'       => 'Threader Earrings',
                'sku'         => 'EARRINGS-005',
                'slug'        => 'threader-earrings',
                'price'       => 34.99,
                'discount'    => 0,
                'category'    => 'earrings',
                'color'       => 'silver',
                'gender'      => 'unisex',
                'description' => 'Modern threader earrings in sterling silver.',
                'summary'     => 'Modern sterling silver threader earrings',
            ],
        ];

        foreach ($products as $data) {
            Product::create($data);
        }
    }
}
